name: deploy

on:
  push:
    branches:
      - dev
jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      working-directory: ./client
    steps:
      - uses: actions/checkout@master
      - run: yarn install --immutable --immutable-cache --check-cache
      - run: npm run build
      - name: deploy to s3 bucket
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --delete
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: "ap-northeast-2"
          SOURCE_DIR: "dist"
